### ISSUE TITLE
Novos atributos como "marca", "cor", "forma" e "carga"

### ISSUE THREAD

**Issue by NunoMartins21** [seczeus/Ruby-OOP-Test#1]
Venho sugerir aqui a adição de atributos como, por exemplo, "marca" e "cor", para tornar a criação de novas canetas num processo mais variado e dinâmico.

Irei tratar de adicionar essas características ao código.

Aproveito também para dizer que este é um projeto muito funcional e inovador, e tenho expectativas muito elevadas para o futuro do mesmo!

**Comment by seczeus** [comment]
Hahahahaha tá-se a armar. Vês como o Ruby é bue simples?

**Comment by NunoMartins21** [comment]
Ya, parece simples. Mas NodeJS também #ficaadica

**Comment by NunoMartins21** [comment]
Pull request com as devidas alterações enviado com sucesso. Tópico fechado.
